name: Linux Release Build
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    name: Linux Release
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Deps
        run: |
          sudo apt update
          sudo apt install -y libsdl2-dev libsdl2-ttf-dev libsdl2-mixer-dev librtmidi-dev nlohmann-json3-dev

      - name: Build
        run: |
          cmake -S . -B out/release -DCMAKE_BUILD_TYPE=Release
          cmake --build out/release --parallel

      - uses: actions/upload-artifact@v4
        with:
          name: system3-linux-release
          path: out/release/system3
          if-no-files-found: error
